// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAshCAsyBTsjlAZs3gp8uoLPrTLd-7KWp8',
    appId: '1:1059422023825:web:220eb8a7f1d67471360f30',
    messagingSenderId: '1059422023825',
    projectId: 'jwtmanager-756f4',
    authDomain: 'jwtmanager-756f4.firebaseapp.com',
    storageBucket: 'jwtmanager-756f4.appspot.com',
    measurementId: 'G-065Y3SJQ91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlGFYuKOGD9mEzxMXgUJoPUXNyP3yfUIc',
    appId: '1:1059422023825:android:4fee5f4eab5b4017360f30',
    messagingSenderId: '1059422023825',
    projectId: 'jwtmanager-756f4',
    storageBucket: 'jwtmanager-756f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvgqJGPLmiMtlQHVx8JbSw1Yn-38CONXg',
    appId: '1:1059422023825:ios:4739164c12d89236360f30',
    messagingSenderId: '1059422023825',
    projectId: 'jwtmanager-756f4',
    storageBucket: 'jwtmanager-756f4.appspot.com',
    iosBundleId: 'com.cavss.jwtWebManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvgqJGPLmiMtlQHVx8JbSw1Yn-38CONXg',
    appId: '1:1059422023825:ios:1042a8c5ddc09b25360f30',
    messagingSenderId: '1059422023825',
    projectId: 'jwtmanager-756f4',
    storageBucket: 'jwtmanager-756f4.appspot.com',
    iosBundleId: 'com.cavss.jwtWebManager.RunnerTests',
  );
}
